name: "bot_${BOT_ID}"

on: 
  schedule: 
  - cron: "0 */6 * * *" 
  workflow_dispatch: 

jobs: 
  run-bot: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python tweety_setup.py
    environment:
      - API_KEY: ${API_KEY}
      - API_KEY_SECRET: ${API_KEY_SECRET}
      - ACCESS_TOKEN : ${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      - BEARER_TOKEN : ${BEARER_TOKEN}

